---
title: "Infer Type Signatures"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Infer Type Signatures}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = ">"
)
```

```{r setup}
library(instrumentr)
```

```{r create-context}

functions <- get_package_function_names("dplyr", public = TRUE, private = FALSE)

application_load_callback <- function(tracer, callback, application) {
    set_r_data(tracer, new.env(parent=emptyenv()))
}

application_unload_callback <- function(tracer, callback, application) {
    print("application_unload_callback")
    data <- get_r_data(tracer)

    print(ls(data))

    for(name in ls(data)) {
        cat(name, ":: ")

        type_sig <- get(name, envir=data)
        l <- length(type_sig)

        index <- 1

        cat("<")
        while(index < l) {
            if(index != 1) {
                cat(", ")
            }
            arg_type <- type_sig[[index]]
            cat(paste(arg_type, collapse = "|"))
            index <- index + 1
        }
        cat("> => ")

        cat(paste(type_sig[[index]], collapse = "|"))

        cat("\n")
    }
}

create_type_sig <- function(n) {
    type_sig <- list()
    index <- 1
    while(index <= n) {
        type_sig[[index]] <- character(0)
        index <- index + 1
    }
    type_sig
}

infer_type <- function(val) {
    typeof(val)
}

merge_type <- function(type_sig, index, type) {
    types <- type_sig[[index]]
    type_sig[[index]] <- unique(c(types, type))
    type_sig
}

call_exit_callback <- function(tracer, callback, application, package, func, call) {
    print("call-exit")
    fun_name <- get_name(func)
    
    print(fun_name)

    parameters <- get_parameters(call)

    data <- get_r_data(tracer)

    if (exists(fun_name, envir=data)) {
        type_sig <- get(fun_name, envir=data)
    }
    else {
        type_sig <- create_type_sig(length(parameters) + 1)
    }

    index <- 1

    for (parameter in parameters) {

        arguments <- get_arguments(parameter)

        if(is_vararg(parameter)) {
            type_sig <- merge_type(type_sig, index, "...")
        }
        else if (length(arguments) == 0) {
            type_sig <- merge_type(type_sig, index, "any")
        }
        else if(!is_evaluated(arguments[[1]])) {
            type_sig <- merge_type(type_sig, index, "any")
        }
        else {
            argument_value <- get_value(arguments[[1]])
            type_sig <- merge_type(type_sig, index, infer_type(argument_value))
        }

        index <- index + 1
    }

    result_type <- "any"

    if(has_result(call)) {
        result <- get_result(call)
        result_type <- infer_type(result)
    }

    type_sig <- merge_type(type_sig, index, result_type)

    assign(fun_name, type_sig, envir=data)
}

tracer <- create_tracer(application_load_callback = application_load_callback,
                        application_unload_callback = application_unload_callback,
                        call_exit_callback = call_exit_callback,
                        functions = functions)
```

```{r trace_code}
result <- trace_code(tracer, {
    suppressPackageStartupMessages(library(dplyr))

    starwars %>%
      filter(species == "Droid")

    starwars %>%
      select(name, ends_with("color"))

    starwars %>%
      mutate(name, bmi = mass / ((height / 100)  ^ 2)) %>%
      select(name:mass, bmi)

    starwars %>%
      arrange(desc(mass))

    starwars %>%
      group_by(species) %>%
      summarise(
          n = n(),
          mass = mean(mass, na.rm = TRUE)
      ) %>%
      filter(n > 1)
})

print(get_value(result))
```
