---
title: "Intercept Package Loading and Unloading"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Intercept Package Loading and Unloading}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = ">"
)
```

```{r setup}
library(instrumentr)
```

```{r create-context}

package_load_callback <- function(tracer, callback, application, package) {
    cat("Loaded", get_name(package), "\n")
}

package_unload_callback <- function(tracer, callback, application, package) {
    cat("Unloaded", get_name(package), "\n")
}

package_attach_callback <- function(tracer, callback, application, package) {
    cat("Attached", get_name(package), "\n")
}

package_detach_callback <- function(tracer, callback, application, package) {
    cat("Detached", get_name(package), "\n")
}

tracing_initialization_callback <- function(tracer, callback, application) {
    print("Trace Entry")
}

tracing_finalization_callback <- function(tracer, callback, application) {
    cat("Trace Exit")
    print(search())
    print(names(get_packages(application)))
}

tracer <- create_tracer(tracing_initialization = tracing_initialization_callback,
                        tracing_finalization = tracing_finalization_callback,
                        package_load = package_load_callback,
                        package_unload = package_unload_callback,
                        package_attach = package_attach_callback,
                        package_detach = package_detach_callback)
```

```{r trace_code}
result <- trace_code(tracer, {
    suppressPackageStartupMessages(library(dplyr))

    starwars %>%
      filter(species == "Droid")

    starwars %>%
      select(name, ends_with("color"))

    starwars %>%
      mutate(name, bmi = mass / ((height / 100)  ^ 2)) %>%
      select(name:mass, bmi)

    starwars %>%
      arrange(desc(mass))

    starwars %>%
      group_by(species) %>%
      summarise(
          n = n(),
          mass = mean(mass, na.rm = TRUE)
      ) %>%
      filter(n > 1)

      unloadNamespace("dplyr")
})

print(get_value(result))

get_exec_stats(tracer)

#get_exec_stats(get_application_load_callback(tracer))
#get_exec_stats(get_application_unload_callback(tracer))
#get_exec_stats(get_call_exit_callback(tracer))
```
