#ifndef INSTRUMENTR_EVENT_H
#define INSTRUMENTR_EVENT_H

#ifdef __cplusplus
extern "C" {
#endif

#include <instrumentr/types.h>

#define INSTRUMENTR_EVENT_TRACING_ENTRY_FUNCTION_T tracing_entry_function_t
#define INSTRUMENTR_EVENT_TRACING_EXIT_FUNCTION_T tracing_exit_function_t
#define INSTRUMENTR_EVENT_PACKAGE_LOAD_FUNCTION_T package_load_function_t
#define INSTRUMENTR_EVENT_PACKAGE_UNLOAD_FUNCTION_T package_unload_function_t
#define INSTRUMENTR_EVENT_PACKAGE_ATTACH_FUNCTION_T package_attach_function_t
#define INSTRUMENTR_EVENT_PACKAGE_DETACH_FUNCTION_T package_detach_function_t
#define INSTRUMENTR_EVENT_BUILTIN_CALL_ENTRY_FUNCTION_T builtin_call_entry_function_t
#define INSTRUMENTR_EVENT_BUILTIN_CALL_EXIT_FUNCTION_T builtin_call_exit_function_t
#define INSTRUMENTR_EVENT_SPECIAL_CALL_ENTRY_FUNCTION_T special_call_entry_function_t
#define INSTRUMENTR_EVENT_SPECIAL_CALL_EXIT_FUNCTION_T special_call_exit_function_t
#define INSTRUMENTR_EVENT_CLOSURE_CALL_ENTRY_FUNCTION_T closure_call_entry_function_t
#define INSTRUMENTR_EVENT_CLOSURE_CALL_EXIT_FUNCTION_T closure_call_exit_function_t
#define INSTRUMENTR_EVENT_EVAL_ENTRY_FUNCTION_T eval_entry_function_t
#define INSTRUMENTR_EVENT_EVAL_EXIT_FUNCTION_T eval_exit_function_t
#define INSTRUMENTR_EVENT_GC_ALLOCATION_FUNCTION_T gc_allocation_function_t
#define INSTRUMENTR_EVENT_VARIABLE_DEFINITION_FUNCTION_T variable_definition_function_t
#define INSTRUMENTR_EVENT_VARIABLE_ASSIGNMENT_FUNCTION_T variable_assignment_function_t
#define INSTRUMENTR_EVENT_VARIABLE_REMOVAL_FUNCTION_T variable_removal_function_t
#define INSTRUMENTR_EVENT_VARIABLE_LOOKUP_FUNCTION_T variable_lookup_function_t
#define INSTRUMENTR_EVENT_CONTEXT_ENTRY_FUNCTION_T context_entry_function_t
#define INSTRUMENTR_EVENT_CONTEXT_EXIT_FUNCTION_T context_exit_function_t
#define INSTRUMENTR_EVENT_PROMISE_FORCE_ENTRY_FUNCTION_T promise_force_entry_function_t
#define INSTRUMENTR_EVENT_PROMISE_FORCE_EXIT_FUNCTION_T  promise_force_exit_function_t
#define INSTRUMENTR_EVENT_PROMISE_VALUE_LOOKUP_FUNCTION_T promise_value_lookup_function_t
#define INSTRUMENTR_EVENT_PROMISE_SUBSTITUTE_FUNCTION_T  promise_substitute_function_t

int instrumentr_event_get_parameter_count(instrumentr_event_t event);

const char*
instrumentr_event_to_string(instrumentr_event_t event);

SEXP instrumentr_event_wrap(instrumentr_event_t event);
instrumentr_event_t instrumentr_event_unwrap(SEXP r_event);

#ifdef __cplusplus
}
#endif

#endif /* INSTRUMENTR_EVENT_H */
