#ifndef INSTRUMENTR_VALUE_H
#define INSTRUMENTR_VALUE_H

#include <instrumentr/api.h>
#include "model.h"

#ifdef __cplusplus
extern "C" {
#endif

/********************************************************************************
 * create
 *******************************************************************************/

instrumentr_value_t instrumentr_value_create(instrumentr_state_t state,
                                             SEXP r_value);

INSTRUMENTR_VALUE_API_MAP(INSTRUMENTR_API_INCLUDER)

#define INSTRUMENTR_VALUE_DECLARE_API(MODEL_TYPE, MODEL_NAME)          \
    bool instrumentr_value_is_##MODEL_NAME(instrumentr_value_t value); \
    instrumentr_##MODEL_NAME##_t instrumentr_value_as_##MODEL_NAME(    \
        instrumentr_value_t value);

INSTRUMENTR_VALUE_DECLARE_API(INSTRUMENTR_MODEL_TYPE_APPLICATION, application)
INSTRUMENTR_VALUE_DECLARE_API(INSTRUMENTR_MODEL_TYPE_UNBOUND, unbound)
INSTRUMENTR_VALUE_DECLARE_API(INSTRUMENTR_MODEL_TYPE_MISSING, missing)
INSTRUMENTR_VALUE_DECLARE_API(INSTRUMENTR_MODEL_TYPE_NULL, null)
INSTRUMENTR_VALUE_DECLARE_API(INSTRUMENTR_MODEL_TYPE_EXTERNALPTR, externalptr)
INSTRUMENTR_VALUE_DECLARE_API(INSTRUMENTR_MODEL_TYPE_WEAKREF, weakref)
INSTRUMENTR_VALUE_DECLARE_API(INSTRUMENTR_MODEL_TYPE_BYTECODE, bytecode)
INSTRUMENTR_VALUE_DECLARE_API(INSTRUMENTR_MODEL_TYPE_S4, s4)
INSTRUMENTR_VALUE_DECLARE_API(INSTRUMENTR_MODEL_TYPE_CHAR, char)
INSTRUMENTR_VALUE_DECLARE_API(INSTRUMENTR_MODEL_TYPE_SYMBOL, symbol)
INSTRUMENTR_VALUE_DECLARE_API(INSTRUMENTR_MODEL_TYPE_CHARACTER, character)
INSTRUMENTR_VALUE_DECLARE_API(INSTRUMENTR_MODEL_TYPE_INTEGER, integer)
INSTRUMENTR_VALUE_DECLARE_API(INSTRUMENTR_MODEL_TYPE_REAL, real)
INSTRUMENTR_VALUE_DECLARE_API(INSTRUMENTR_MODEL_TYPE_LOGICAL, logical)
INSTRUMENTR_VALUE_DECLARE_API(INSTRUMENTR_MODEL_TYPE_COMPLEX, complex)
INSTRUMENTR_VALUE_DECLARE_API(INSTRUMENTR_MODEL_TYPE_RAW, raw)
INSTRUMENTR_VALUE_DECLARE_API(INSTRUMENTR_MODEL_TYPE_ENVIRONMENT, environment)
INSTRUMENTR_VALUE_DECLARE_API(INSTRUMENTR_MODEL_TYPE_FUNCTION, function)
INSTRUMENTR_VALUE_DECLARE_API(INSTRUMENTR_MODEL_TYPE_PROMISE, promise)

#ifdef __cplusplus
}
#endif

#endif /* INSTRUMENTR_VALUE_H */
