on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: clang-tidy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - uses: r-lib/actions/setup-r@master

      - name: Add PPA
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update -q

      - name: Install clang
        run: |
          sudo apt-get install clang-10 -qy
          sudo apt-get install clang-tidy-10 -qy

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install libcurl
        run: |
          sudo apt-get install libcurl4 libcurl4-openssl-dev -qy

      - name: Install dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("devtools")
        shell: Rscript {0}

      - name: Run clang-tidy
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: make clang-tidy SCAN_BUILD=scan-build-10
  
