on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: cppcheck

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Add PPA
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update -q

      - name: Install gcc
        run: |
          sudo apt-get install gcc-9 -qy
          sudo apt-get install g++-9 -qy

      - name: Install cppcheck
        run: |
          wget https://github.com/danmar/cppcheck/archive/2.1.tar.gz -P /tmp/
          tar -xvf /tmp/2.1.tar.gz -C /tmp/
          sudo make --directory=/tmp/cppcheck-2.1 install SRCDIR=build MATCHCOMPILER=yes FILESDIR=/usr/share/cppcheck HAVE_RULES=yes CXXFLAGS="-O2 -DNDEBUG -Wall -Wno-sign-compare -Wno-unused-function" || true

      - name: Run cppcheck
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: make cppcheck
  
