on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: cppcheck

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Install cppcheck
        run: sudo apt-get install cppcheck

      - name: Run cppcheck
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: make cppcheck
