on:
  push:
    branches:
      - master
      - c-api
  pull_request:
    branches:
      - master
      - c-api

name: rchk

jobs:
  rchk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: r-lib/actions/run-rchk@master
      with:
        package:
